CREATE TABLE bancos (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    criado_em DATE NOT NULL DEFAULT CURRENT_DATE,
    saldo DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    removido BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);
